#!/usr/bin/env python3
"""
Calculate how many stocks are generated by the current implementation
"""


def calculate_stock_count():
    """Calculate the number of stocks generated by _is_likely_valid_stock_code"""

    def _is_likely_valid_stock_code(code: int) -> bool:
        """Check if a stock code is likely to be valid."""
        # Include most codes but skip some sparse ranges
        if code < 1300:
            return code % 5 == 0  # Sample every 5th code in low ranges
        return True

    count = 0
    for code in range(1000, 10000):
        if _is_likely_valid_stock_code(code):
            count += 1

    return count


def calculate_rotation_distribution(total_stocks, groups=5):
    """Calculate how stocks are distributed across rotation groups"""
    stocks_per_group = total_stocks // groups
    remainder = total_stocks % groups

    group_sizes = []
    for i in range(groups):
        size = stocks_per_group + (1 if i < remainder else 0)
        group_sizes.append(size)

    return group_sizes


if __name__ == "__main__":
    print("=== Stock Count Analysis ===")

    # Calculate total stocks
    total_stocks = calculate_stock_count()
    print(f"Total stocks generated: {total_stocks}")

    # Calculate distribution for 5 groups (current)
    print(f"\n=== Current 5-Group Rotation ===")
    group_sizes_5 = calculate_rotation_distribution(total_stocks, 5)
    for i, size in enumerate(group_sizes_5):
        weekdays = ["月曜日", "火曜日", "水曜日", "木曜日", "金曜日"]
        print(f"{weekdays[i]}: {size} stocks")

    # Calculate distribution for 10 groups
    print(f"\n=== Proposed 10-Group Rotation ===")
    group_sizes_10 = calculate_rotation_distribution(total_stocks, 10)
    for i, size in enumerate(group_sizes_10):
        print(f"Group {i+1}: {size} stocks")

    # Calculate distribution for 12 groups
    print(f"\n=== Proposed 12-Group Rotation ===")
    group_sizes_12 = calculate_rotation_distribution(total_stocks, 12)
    for i, size in enumerate(group_sizes_12):
        print(f"Group {i+1}: {size} stocks")

    # Calculate with reduced stock selection
    print(f"\n=== Reduced Stock Selection Analysis ===")

    def _is_likely_valid_stock_code_reduced(code: int) -> bool:
        """Reduced stock selection - every 10th code in low ranges"""
        if code < 1300:
            return code % 10 == 0  # Sample every 10th code in low ranges
        elif code < 5000:
            return code % 2 == 0  # Sample every 2nd code in mid ranges
        else:
            return code % 3 == 0  # Sample every 3rd code in high ranges

    reduced_count = 0
    for code in range(1000, 10000):
        if _is_likely_valid_stock_code_reduced(code):
            reduced_count += 1

    print(f"Reduced total stocks: {reduced_count}")

    # Calculate distribution for reduced stocks with 5 groups
    group_sizes_reduced = calculate_rotation_distribution(reduced_count, 5)
    for i, size in enumerate(group_sizes_reduced):
        weekdays = ["月曜日", "火曜日", "水曜日", "木曜日", "金曜日"]
        print(f"{weekdays[i]}: {size} stocks")
